version: 0.0
os: linux
files:
  - source: /index.html
    destination: /data/first-project
  - source: /package.json
    destination: /data/first-project
  - source: /server.js
    destination: /data/first-project
hooks:
  BeforeInstall:   
  AfterInstall:    
  ApplicationStop:   
